name: tss
services:
  web:
    image: node:20-alpine
    working_dir: /app
    command: sh -c "corepack enable && corepack prepare pnpm@10.19.0 --activate && pnpm i && pnpm dev"
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
      - "${HMR_PORT:-24678}:${HMR_PORT:-24678}"   # Vite HMR (Nuxt)
    environment:
      - NODE_ENV=development
      - COREPACK_ENABLE_DOWNLOAD_PROMPT=0
      - NUXT_HOST=0.0.0.0
      - APP_PORT=${APP_PORT:-3000}
      - NUXT_PORT=${APP_PORT:-3000}
      - HMR_PORT=${HMR_PORT:-24678}
      - CONTENT_WS_DISABLE=1
    volumes:
      - ./:/app
      - pnpm-store:/root/.local/share/pnpm/store
      - node_modules:/app/node_modules
    tty: true
    stdin_open: true
volumes:
  pnpm-store:
  node_modules:

